- name: Set admin password
  include_tasks: set-admin-password.yml
  when:
    - aem_security_admin_user | default("") | string | length > 0
    - aem_security_admin_password_new | default("") | string | length > 0
    - aem_security_admin_password_old | default("") | string | length > 0
    - aem_security_admin_password_new != aem_security_admin_password_old
